# Generated by Django 6.0.2 on 2026-03-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_user_birth_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="images/Avatar/default.jpeg", max_length=100
            ),
        ),
    ]
