# Generated by Django 6.0.2 on 2026-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="cover",
            field=models.ImageField(default="covers/default.jpg", upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="download_link",
            field=models.FileField(blank=True, null=True, upload_to="songs/downloads/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="link",
            field=models.FileField(upload_to="songs/"),
        ),
    ]
