# Generated by Django 6.0.2 on 2026-03-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_alter_song_cover_alter_song_download_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpeg", upload_to="avatars/"
            ),
        ),
    ]
