# Generated by Django 6.0.2 on 2026-03-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_cover_alter_song_download_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='link',
        ),
        migrations.AlterField(
            model_name='song',
            name='download_link',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
