# Generated by Django 6.0.2 on 2026-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
