# Generated by Django 6.0.2 on 2026-03-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_song_link_alter_song_download_link'),
        ('music', '0006_user_date_joined'),
    ]

    operations = [
    ]
