# Generated by Django 6.0.2 on 2026-03-08 19:52

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_merge_20260308_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='covers/default.jpg', upload_to=music.models.song_cover_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='download_link',
            field=models.FileField(blank=True, null=True, upload_to=music.models.song_audio_path),
        ),
    ]
