# Generated by Django 6.0.2 on 2026-03-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_recentplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_played_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.song'),
        ),
        migrations.DeleteModel(
            name='RecentPlay',
        ),
    ]
