# Generated by Django 6.0.2 on 2026-03-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_user_last_played_song_delete_recentplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, default='Unknown Album', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='arrangement',
            field=models.CharField(blank=True, default='Unknown Artist', max_length=100, null=True),
        ),
    ]
