# Generated by Django 6.0.2 on 2026-03-12 00:10

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_song_album_alter_song_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.FileField(blank=True, null=True, upload_to=music.models.song_lrc_path),
        ),
    ]
