# Generated by Django 6.0.2 on 2026-03-12 03:54

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.FileField(blank=True, default='1145141919810', null=True, upload_to=music.models.song_lrc_path),
        ),
    ]
