# Generated by Django 6.0.2 on 2026-03-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_song_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identity',
        ),
    ]
