# Generated by Django 6.0.2 on 2026-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_remove_user_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='introduction',
            field=models.TextField(blank=True, default='No Description', null=True),
        ),
    ]
