# Generated by Django 6.0.2 on 2026-03-14 16:05

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_playlist_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_playlists', to='music.user'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='playlists/default_playlist.png', upload_to=music.models.playlist_cover_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='covers/default_cover.jpg', upload_to=music.models.song_cover_path),
        ),
    ]
