# Generated by Django 6.0.2 on 2026-03-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_playlist_favorited_by_alter_playlist_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
