# Generated by Django 6.0.2 on 2026-03-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_remove_user_membership_delete_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_played_song',
        ),
    ]
