# Generated by Django 6.0.2 on 2026-05-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_comment_liked_by_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
