# Generated by Django 6.0.2 on 2026-05-01 08:05

import django.db.models.deletion
from django.db import migrations, models


def seed_playlist_song_positions(apps, schema_editor):
    Playlist = apps.get_model('music', 'Playlist')
    PlaylistSong = apps.get_model('music', 'PlaylistSong')
    through_model = Playlist.songs.through

    rows = []
    for playlist in Playlist.objects.all().order_by('id'):
        relations = through_model.objects.filter(playlist_id=playlist.id).order_by('id')
        for position, relation in enumerate(relations, start=1):
            rows.append(PlaylistSong(
                playlist_id=playlist.id,
                song_id=relation.song_id,
                position=position,
            ))

    if rows:
        PlaylistSong.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_alter_song_options_song_track_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_positions', to='music.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_positions', to='music.song')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['playlist', 'position'], name='music_playl_playlis_b22825_idx')],
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.RunPython(seed_playlist_song_positions, migrations.RunPython.noop),
    ]
