# Generated by Django 6.0.2 on 2026-05-01 08:38

import django.db.models.deletion
from django.db import migrations, models


def seed_favorite_song_positions(apps, schema_editor):
    User = apps.get_model('music', 'User')
    FavoriteSongPosition = apps.get_model('music', 'FavoriteSongPosition')
    through_model = User.favorite_songs.through

    rows = []
    for user in User.objects.all().order_by('id'):
        relations = through_model.objects.filter(user_id=user.id).order_by('id')
        for position, relation in enumerate(relations, start=1):
            rows.append(FavoriteSongPosition(
                user_id=user.id,
                song_id=relation.song_id,
                position=position,
            ))

    if rows:
        FavoriteSongPosition.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_playlistsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSongPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_positions', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_song_positions', to='music.user')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['user', 'position'], name='music_favor_user_id_fc4317_idx')],
                'unique_together': {('user', 'song')},
            },
        ),
        migrations.RunPython(seed_favorite_song_positions, migrations.RunPython.noop),
    ]
